# Generated by Django 2.2.13 on 2021-09-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_auto_20210910_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='temp',
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
