# Generated by Django 2.0.7 on 2021-09-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
